"""knowledge_bases table + documents.kb_id

Revision ID: bce5e7501f7c
Revises: ed25bd7e7382
Create Date: 2026-08-30 10:37:46.931764

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bce5e7501f7c"
down_revision: str | Sequence[str] | None = "ed25bd7e7382"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_bases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=False),
        sa.Column("department", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("documents", sa.Column("kb_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_documents_kb_id"), "documents", ["kb_id"], unique=False)
    op.create_foreign_key(None, "documents", "knowledge_bases", ["kb_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_index(op.f("ix_documents_kb_id"), table_name="documents")
    op.drop_column("documents", "kb_id")
    op.drop_table("knowledge_bases")
    # ### end Alembic commands ###
