"""content_hash + ingestion_reports (data cleaning)

Revision ID: ed25bd7e7382
Revises: 4b2634627afe
Create Date: 2026-08-20 13:25:57.979557

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed25bd7e7382"
down_revision: str | Sequence[str] | None = "4b2634627afe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("doc_id", sa.String(length=128), nullable=False),
        sa.Column("total_blocks", sa.Integer(), nullable=False),
        sa.Column("filtered_blocks", sa.Integer(), nullable=False),
        sa.Column("dedup_skipped", sa.Integer(), nullable=False),
        sa.Column("avg_chunk_length", sa.Float(), nullable=False),
        sa.Column("empty_pages", sa.Integer(), nullable=False),
        sa.Column("noise_reasons", sa.Text(), nullable=False),
        sa.Column("llm_cleaned", sa.Integer(), nullable=False),
        sa.Column("llm_fallback", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingestion_reports_doc_id"), "ingestion_reports", ["doc_id"], unique=True
    )
    op.add_column("documents", sa.Column("content_hash", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_documents_content_hash"), "documents", ["content_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_content_hash"), table_name="documents")
    op.drop_column("documents", "content_hash")
    op.drop_index(op.f("ix_ingestion_reports_doc_id"), table_name="ingestion_reports")
    op.drop_table("ingestion_reports")
    # ### end Alembic commands ###
